modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="adventuresystems"
version="${file.jarVersion}"
displayName="Adventure Systems"
authors="XYAT"
description='''
Adventure systems for Curios, wallets, FTB quest interaction, and contextual tips.
'''

[[dependencies.adventuresystems]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.adventuresystems]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.adventuresystems]]
modId="kineticcore"
mandatory=true
versionRange="[26.9.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="curios"
mandatory=true
versionRange="[5.10.0,)"
ordering="AFTER"
side="BOTH"


[[dependencies.adventuresystems]]
modId="refinedstorage"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="sophisticatedbackpacks"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="ftblibrary"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="ftbquests"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="ftbteams"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
