modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPLv3"

[[mods]]
modId="adventuresystems"
version="${file.jarVersion}"
displayName="Adventure Systems"
authors="XYAT"
description='''
Adventure systems for Curios, wallets, FTB quest interaction, and contextual tips.
'''

[[dependencies.adventuresystems]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.adventuresystems]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.adventuresystems]]
modId="kineticcore"
type="required"
versionRange="[26.10.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="curios"
type="required"
versionRange="[9,)"
ordering="AFTER"
side="BOTH"


[[dependencies.adventuresystems]]
modId="refinedstorage"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="ftblibrary"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="ftbquests"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="ftbteams"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adventuresystems]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

${mixin_configs}
